require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.

RSpec.describe "/questionnaires", type: :request do
  let(:questionnaire) { Questionnaire.find(:test) }

  describe "GET /show" do
    it "renders a successful response" do
      get questionnaire_url(id: questionnaire.id)
      expect(response).to be_successful
    end
  end

  describe "PATCH /update" do
    it "renders a response" do
      get questionnaire_url(id: questionnaire.id)
      expect(response).to be_successful
    end
  end
end
